"""empty message

Revision ID: 43b888b16f89
Revises: dc2d3258cd25
Create Date: 2022-09-21 15:45:48.966375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43b888b16f89'
down_revision = 'dc2d3258cd25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('ticks', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'ticks')
    # ### end Alembic commands ###
