"""empty message

Revision ID: a4852d1e4de2
Revises: 
Create Date: 2022-09-20 15:11:49.614883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4852d1e4de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('game',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('runnerUp', sa.Integer(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('clients', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['runnerUp'], ['user.id'], ),
    sa.ForeignKeyConstraint(['winner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userGames',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userGames')
    op.drop_table('game')
    op.drop_table('user')
    # ### end Alembic commands ###
